### PR TITLE
getName() and reset() added.

### PR DESCRIPTION
**Pull request by qliqdev**
I've added getName() function same return as ios, but i guess it will be returned with dot at the begining of name (Ex: .stencil)

Also added reset() function

### CODE REVIEW

**Comment by qliqdev** [comment]
@johnborges Hi, John! Can you check my PL, please.

**Comment by johnborges** [comment]
will do. I want to test it too.

**Comment by johnborges** [comment]
I thought I had docgen setup with this project. Ill take that todo. 

@qliqdev Would you mind just updating the documentation in `README.md` to include the new property you added on `ResetOptions`

**Comment by qliqdev** [comment]
@johnborges added 

`<docgen-index>` and `<docgen-api>` for docgen autogeneration

**Pull request merged**
